#!/bin/bash

slurmSLAVE=MBL-SLA-GS.sh

for size in 8 #12 16 20
do
echo "L = "$size

for disorder in 1.0 #2.0 3.0 4.0 5.0 6.0 
do
echo "Delta = " $disorder

for dis in 0 #1
do
echo "Dis_gen = " $dis

jobname=MBL-GS-L$size-D$disorder-Dis$dis
slurmscript=$jobname

sed "s/SIZE/$size/g" $slurmSLAVE | sed "s/DISORDER/$disorder/g" | sed "s/DIS_FLAG/$dis/g" | sed "s/MYJOBNAME/$jobname/g" > $slurmscript

echo "submitting " $slurmscript
sbatch $slurmscript
sleep 2

done
done
done
