#!/bin/bash

slurmSLAVE=MBL-SLA-Neel.sh

for size in 20
do
echo "L = "$size

for disorder in 1.0 2.0 3.0 4.0 5.0 6.0 
do
echo "Delta = " $disorder

for disin in 0 1
do
echo "Dis_flag = "$dis
echo $jobname

jobname=MBLNeel-L$size-D$disorder-Dflag$dis
slurmscript=$jobname

sed "s/SIZE/$size/g" $slurmSLAVE | sed "s/DISORDER/$disorder/g" | sed "s/DIS_FLAG/$dis/g" | sed "s/MYJOBNAME/$jobname/g" > $slurmscript

echo "submitting " $slurmscript
sbatch $slurmscript
sleep 2
done
done
done
