#!/bin/bash

slurmSLAVE=MBL-SLA-Neel.sh

for size in 20
do
echo "L = "$size

for disorder in 1.0 2.0 3.0 4.0 5.0 6.0 
do
echo "Delta = " $disorder

jobname=MBLNeel-L$size-D$disorder
slurmscript=$jobname

for disin in 0.5
do
echo "Delta_in = "$disin
echo $jobname

sed "s/SIZE/$size/g" $slurmSLAVE | sed "s/DISORDER/$disorder/g" | sed "s/DIS_IN/$disin/g" | sed "s/MYJOBNAME/$jobname/g" > $slurmscript

echo "submitting " $slurmscript
sbatch $slurmscript
sleep 2
done
done
done
