#!/bin/bash

slurmSLAVE=MBL-SLA-Long.sh

for size in 14
do
echo "L = "$size

for disorder in 2.0 7.0 8.0 15.0 
do
echo "Delta = " $disorder

for dis in 0 1
do
echo "Dis_gen = "$dis

for intflag in 0 1
do
echo "Interaction = "$intflag

jobname=MBLLong-L$size-D$disorder-Dis$dis-Int-$intflag
slurmscript=$jobname

sed "s/SIZE/$size/g" $slurmSLAVE | sed "s/DISORDER/$disorder/g"| sed "s/DIS_FLAG/$dis/g" | sed "s/INT_FLAG/$intflag/g" |sed "s/MYJOBNAME/$jobname/g" > $slurmscript

echo "submitting " $slurmscript
sbatch $slurmscript
sleep 2

done
done
done
done
